name: CI - Build and Test Spring Boot App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # 3️⃣ Build and run tests
      - name: Build with Maven
        run: mvn -B clean verify

      # 4️⃣ Package the application
      - name: Package Spring Boot App
        run: mvn -B package -DskipTests

      # 5️⃣ Upload the JAR artifact (optional)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: target/*.jar
